### ISSUE TITLE
Add openebs in cncf.ci dashboard

### ISSUE THREAD

**Issue by bhaskarhc** [mayadata-io/oep-e2e#126]
**Title :**
- Add Openebs to cncf.ci

**Short Description :**

- To add another CNCF-hosted project to cncf.ci Dashboard .
- Now openebs is in Sandbox Project ,  cncf dashboard contains Sandbox and  Incubating Projects .

**Tasks :**

- [ ] Have a repository in `crosscloudci/openebs-configuration`
- [ ] Create cncf.yaml file by following  [CONTRIBUTION.md](https://github.com/crosscloudci/crosscloudci/blob/master/CONTRIBUTING.md) in  `crosscloudci/openebs-configuration` .
- [ ] Add e2e-tests 

**Tested ?**

- [ ] cidev.cncf.ci
- [ ] dev.cncf.ci
- [ ] staging.cncf.ci
- [ ] cncf.ci (production)
